name: Security Code Scan
on:
  pull_request:
    branches:
      - develop
      - master
      - main
      - staging

permissions:
  contents: read

jobs:
  bearer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout current repo
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: bearer/bearer-action@v1.0
        name: Run Report
        id: report
