name: Secrets Scan
on:
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout current repo
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: trufflesecurity/trufflehog@v3.23.0
        name: TruffleHog with ignorefile
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --no-verification -x .trufflehogignore
